version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - '5556:5432'
# version: '3.9'
# services:
#   postgres:
#     container_name: postgres
#     image: postgres:12-alpine
#     volumes:
#       - ../log:/root/log:cached
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - PSQL_HISTFILE=/root/log/.psql_history
#       - POSTGRES_DB=postgres
#     ports:
#       - '5432:5556'
